import { SidebarItem } from '../models/sidebar-item.model';

export const SIDEBAR_ROUTES: SidebarItem[] = [
  {
    id: 1,
    label: 'Dashboard',
    icon: 'fa-home',
    route: '/',
    isActive: true,
    isExpanded: false,
  },
  {
    id: 2,
    label: 'Apps',
    icon: 'fa-th-large',
    route: '/apps',
    isActive: false,
    isExpanded: false,
    children: [
      { id: 21, label: 'Chat', icon: 'fa-comments', route: '/apps/chat', isActive: false },
      { id: 22, label: 'Email', icon: 'fa-envelope', route: '/apps/email', isActive: false },
      {
        id: 23,
        label: 'Calendar',
        icon: 'fa-calendar-alt',
        route: '/apps/calendar',
        isActive: false,
      },
    ],
  },
  {
    id: 3,
    label: 'Pages',
    icon: 'fa-file-alt',
    route: '/pages',
    isActive: false,
    isExpanded: false,
    children: [
      { id: 31, label: 'Users', icon: 'fa-users', route: '/pages/users', isActive: false },
      {
        id: 32,
        label: 'Profile',
        icon: 'fa-user-circle',
        route: '/pages/profile',
        isActive: false,
      },
      { id: 33, label: 'Settings', icon: 'fa-cog', route: '/pages/settings', isActive: false },
    ],
  },
  {
    id: 4,
    label: 'Auth',
    icon: 'fa-user-shield',
    route: '/auth',
    isActive: false,
    isExpanded: false,
    children: [
      { id: 40, label: 'Client Context', icon: 'fa-bullseye', route: '/auth/context', isActive: false },
      { id: 41, label: 'Clients', icon: 'fa-key', route: '/auth/clients', isActive: false },
      { id: 42, label: 'Users', icon: 'fa-users', route: '/auth/users', isActive: false },
      { id: 43, label: 'Role Groups', icon: 'fa-layer-group', route: '/auth/role-groups', isActive: false },
      { id: 44, label: 'Roles', icon: 'fa-user-tag', route: '/auth/roles', isActive: false },
      {
        id: 45,
        label: 'Permission Groups',
        icon: 'fa-object-group',
        route: '/auth/permission-groups',
        isActive: false,
      },
      { id: 46, label: 'Permissions', icon: 'fa-shield-alt', route: '/auth/permissions', isActive: false },
      { id: 47, label: 'OAuth Tools', icon: 'fa-plug', route: '/auth/oauth', isActive: false },
      { id: 48, label: 'MFA & Email', icon: 'fa-lock', route: '/auth/mfa', isActive: false },
    ],
  },
];
